### ISSUE TITLE
🐛 Modified filenames have poor contrast when hovering

### ISSUE THREAD

**Issue by SpeedyLom** [SpeedyLom/dislexic-vscode#12]
### Describe the bug
Hovering over changed files in the explorer make them difficult to read because the foreground colour is green and the background colour is really light grey.

### To Reproduce
Steps to reproduce the behaviour:
1. Open a folder with a VCS
2. Change a file
3. Hover over the file in the explorer

### Expected behaviour
The hover colour (background) should be darker so that it is easier to see the names of the files.

### Software/device information
Use the `Help: About` pop-up to copy the information to the clipboard.

Within `code` press <kbd>Ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd> to launch the command palette then run:

```
help:about
```
```
Version: 1.66.1
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:51:26.173Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.16.19-200.fc35.x86_64
```
 - Extension version `v1.0.1`

### Additional context
None

**Comment by EliseWei** [comment]
Hello, and thank you so much for building this theme! I teach programming and I've been looking at ways to make live coding demos more accessible. This has been a great starting point!
Since this particular green also appears in the light-background tabs, I found `#3f9b4a` works well for both (or my eyes), though it doesn't quite pass WCAG contrast checks.

**Comment by SpeedyLom** [comment]
Hey @EliseWei,

You're welcome, it is so cool to think that it could be useful in an academic setting.

Thank you for the suggestion I will definitely check it out. 

I haven't been worried about meeting any particular standards just yet, I wanted to get the base colours I have been using in PhpStorm ported over. 

I think I'll add an issue for something like the WCAG contrast checks for a future version as it could be useful overall.

Thanks for taking the time to message.

**Comment by EliseWei** [comment]
Awesome. If you would like a hand with anything, let me know. I've been making some customizations locally, to get a lower-contrast theme overall, as the student I tested this with also experiences visual stress. Could maybe be an alternate version of the theme?
Cheers. :)

**Comment by SpeedyLom** [comment]
Thanks, I'll probably need help with something.

I'm not against different variations of the theme and I'd be open to setting up repos for those.

I have added some recommendations to the readme that I use to help with visual stress, line height really helps me.
